### ISSUE TITLE
Unable to download the demo_TUIO file

### ISSUE THREAD

**Issue by SiddiqMohammed** [JpHoooo/unity-tuio-rplidar#1]
Hi, 
Is there somewhere else where you could host the demo file? Baidu doesn't work properly outside of China. If you could add the file to this repo as well then that would be great.

Thanks

**Comment by JpHoooo** [comment]
Hi,
I am very sorry that it took so long to notice your message. The file has been placed in Google Cloud Disk, and welcome to download it.
https://drive.google.com/file/d/1g8julT8AvS8T78rENHXxvgM1pD7uEdcQ/view?usp=sharing

**Comment by SiddiqMohammed** [comment]
Thanks a lot. It's working perfectly!
